### ISSUE TITLE
test failure in local machine

### ISSUE THREAD

**Issue by neighborhood999** [lukechilds/merge-images#62]
Hi @lukechilds ! Thanks to your awesome merge-images package.

I forked and clone to my local machine and install dependencies and I run the test I got two failure test:

```shell
unit › mergeImages encodes jpeg format

  /Users/.../merge-images/test/unit.js:32

   31:
   32:     t.true(b64 === expectedB64);
   33:   });

  Value is not `true`:

  false

  b64 === expectedB64
  => false

  expectedB64
  => 'data:image/jpeg;base64,...
```

```shell
unit › mergeImages uses custom jpeg quality

  /Users/.../merge-images/test/unit.js:88

   87:
   88:   t.true(b64 === expectedB64);
   89: });

  Value is not `true`:

  false

  b64 === expectedB64
  => false

  expectedB64
  => 'data:image/jpeg;base64,...
```

I made images by the output encode data and try again test, I pass tests. Here is my [PR](https://github.com/lukechilds/merge-images/pull/61), but its failure on Travis CI.

This is my environment:

```
OS: macOS 10.13.6
node: v9.8.0
npm: 5.6.0
```

Thanks! Have a good day.

**Comment by lukechilds** [comment]
Yeah, that's expected, happens for me too.

I believe it's because whatever `node-canvas` uses for rendering is different on macOS/Linux so the binary result varies slightly.

I wrote the tests for Linux so CI would work and we can easily see if anyone is making a breaking change. It is a pain for running tests locally though.

It would be possible to add a check in the tests to compare against different images based on the OS so it can pass on both Mac and Linux. Although that may become out of sync.

**Comment by neighborhood999** [comment]
@lukechilds OK, Thanks for your explanation!
